# The URL the site will be built for
base_url = "https://mtlks.com"

title = "MTLKS"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Theme
theme = "kita"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

[extra.profile]
name = "Matthew T. Liew K.S."
bio = "Tech Enthusiast | DevOps | NixOS i3"
avatar_url = "images/profile.png"
avatar_invert = false

[[extra.profile.social]]
name = "github"
url = "https://github.com/mtlks"

[[extra.profile.social]]
name = "linkedin"
url = "https://linkedin.com/in/mtlks"

[[extra.menu]]
name = "/ home"
url = "$BASE_URL"

[[extra.menu]]
name = "/ projects"
url = "$BASE_URL/projects"

[[extra.menu]]
name = "/ log"
url = "$BASE_URL/log"

[extra.footer]
since = 2024
